# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroidCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('primary_function', models.CharField(max_length=140)),
                ('appears_in', models.ManyToManyField(to='movies.Movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HumanCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('home_planet', models.CharField(max_length=140)),
                ('appears_in', models.ManyToManyField(to='movies.Movie')),
                ('friends', models.ManyToManyField(to='characters.HumanCharacter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
