# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('year', models.PositiveIntegerField(default=1980)),
            ],
        ),
    ]
